

#define MAXAPICALLS				0x22

#define CMD_API_FILLBLOCK			0x00
#define CMD_API_FILLSCREEN			0x01
#define CMD_API_INVERSEBLOCK		0x02
#define CMD_API_VLINE				0x03
#define CMD_API_HLINE				0x04
#define CMD_API_RECTANGLE			0x05
#define CMD_API_CURSORSTATUS		0x06
#define CMD_API_CURSORSHAPE			0x07
#define CMD_API_FONT				0x08
#define CMD_API_SCROLLUP			0x09
#define CMD_API_SCROLLDN			0x0A
#define CMD_API_SCROLLLEFT			0x0B
#define CMD_API_SCROLLRIGHT			0x0C
#define CMD_API_RESTORELCD			0x0D
#define CMD_API_BACKUPLCD			0x0E
#define CMD_API_RESTOREHELPLCD		0x0F
#define CMD_API_BACKUPHELPLCD		0x10
#define CMD_API_SETINDION			0x11
#define CMD_API_SETINDIOFF			0x12
#define CMD_API_SETTONE				0x13
#define CMD_API_MAKEWARNTONE		0x14
#define CMD_API_SETPOWERMODE		0x15
#define CMD_API_MASKSYMKEY			0x11
#define CMD_API_MASKFNTKEY			0x17
#define CMD_API_CLEARCHARBUF		0x18
#define CMD_API_SETKEYTONE			0x19
#define CMD_API_STRINGMENU			0x1A
#define CMD_API_VSCROLLBAR			0x1B
#define CMD_API_SHADOWEDGERECT		0x1C
#define CMD_API_STRINGDIALOGBOX		0x1D
#define CMD_API_STRINGPHONEMENU		0x1E
#define CMD_API_BUTTON				0x1F
#define CMD_API_CHECKBOX			0x20
#define CMD_API_RADIOBUTTON			0x21
#define CMD_API_LOADIMAGE			0x22
#define CMD_API_PUTIMAGE			0x23
#define CMD_API_ALLOCIMAGE			0x24
#define CMD_API_GETIMAGE			0x25
#define CMD_API_DELAY1MS			0x26
#define CMD_API_DELAY250MS			0x27
#define CMD_API_DELAY1S				0x28

#define CMD_API_MAX				    0x28

void cmd_APICall();
void InitVMAPI();
